{% set name = "name_that_hash" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6978a2659ce6d38c330ab8057b78bccac00bc3e87138f2774bec3af2276b0303

build:
  number: 0
  noarch: python
  entry_points:
    - name-that-hash = name_that_hash.runner:main
    - nth = name_that_hash.runner:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - click >=7.1.2,<9.0.0
    - python >=3.6,<4.0
    - rich >=9.9,<11.0

test:
  imports:
    - name_that_hash
  commands:
    - pip check
    - name-that-hash --help
    - nth --help
  requires:
    - pip

about:
  home: https://pypi.org/project/name-that-hash/
  summary: The Modern Hash Identification System
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    Have you ever come across a hash such as 5f4dcc3b5aa765d61d8327deb882cf99
     and wondered what type of hash that is? Name-that-hash will name that hash
     type!

extra:
  recipe-maintainers:
    - thewchan
