{% set name = "name_that_hash" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6978a2659ce6d38c330ab8057b78bccac00bc3e87138f2774bec3af2276b0303

build:
  number: 0
  noarch: python
  entry_points:
    - name-that-hash = name_that_hash.runner:main
    - nth = name_that_hash.runner:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6.2,<4.0.0
  run:
    - click >=7.1.2
    - python >=3.6.2,<4.0.0
    - rich >=11.0.0

test:
  imports:
    - name_that_hash
  commands:
    - pip check
    - name-that-hash --help
    - nth --help
  requires:
    - pip

about:
  home: https://nth.skerritt.blog/
  dev_url: https://github.com/HashPals/Name-That-Hash
  summary: The Modern Hash Identification System
  license: GPL-3.0-only
  license_file: LICENSE
  description: The Modern Hash Identification System

extra:
  recipe-maintainers:
    - thewchan
